
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
   
  grpc-service:
    # path to the Dockerfile for the gRPC service. Can even be a git repo
    container_name: grpc-service
    build: grpc/
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: itemsdb

    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50051"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "50051:50051"
    
  rest-service:
    container_name: rest-service
    build: rest/
    depends_on:
      - grpc-service
    ports:
      - "5000:5000"
    environment:
      # The address at which REST calls gRPC servic
      GRPC_HOST: grpc-service
      GRPC_PORT: 50051
      