{
 "title": "Items Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "95th percentile latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "http"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket[5m])) by (le))",
     "legendFormat": "grpc"
    }
   ]
  },
  {
   "title": "Rate Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handling_seconds_count[1m]))",
     "legendFormat": "grpc"
    },
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "http"
    }
   ]
  },
  {
   "title": "Error Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m]))",
     "legendFormat": "http"
    }
   ]
  }
 ]
}